title: Zhixuan Liu's Homepage
page-top-title: Zhixuan Liu
top-section-bg-text: Be what you wanna be
home-subtitle: 刘志轩&ensp;|&ensp;Zhixuan Liu
copyright-text: '&copy; Zhixuan Liu 2025. All Rights Reserved.'